---
version: "2"
services:
  app:
    build: ebot-csgo
    links:
      - mysql
    ports:
      - "12360:12360"
  web:
    build: ebot-csgo-web
    links:
      - mysql
      - app
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7.15
    environment:
      MYSQL_USER: ebotv3
      MYSQL_PASSWORD: ebotv3
      MYSQL_DATABASE: ebotv3
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
